name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:       # Optional: allows manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://iep-harmony-backend.onrender.com/health
